apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: meteo
    database: meteo
    isDefault: true
    editable: false
    secureJsonData:
      password: meteo
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
