# Add your target locations here.
locations:
  - id: vilnius
    name: Vilnius
    latitude: 54.6872
    longitude: 25.2797
    timezone: Europe/Vilnius

  - id: kaunas
    name: Kaunas
    latitude: 54.8985
    longitude: 23.9036
    timezone: Europe/Vilnius
